"""initial schema

Revision ID: 390dfb45e167
Revises: 
Create Date: 2026-01-15 15:58:35.034314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390dfb45e167'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('jokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_tn', sa.Text(), nullable=False),
    sa.Column('text_fr', sa.Text(), nullable=True),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('era', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('acceptability', sa.String(length=50), nullable=True),
    sa.Column('delivery_type', sa.String(length=50), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('rhythm', sa.String(length=50), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jokes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jokes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jokes_is_published'), ['is_published'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jokes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jokes_is_published'))
        batch_op.drop_index(batch_op.f('ix_jokes_created_at'))

    op.drop_table('jokes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
