"""Add class diagram models

Revision ID: 591a0de18800
Revises: 390dfb45e167
Create Date: 2026-01-19 20:49:46.881727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591a0de18800'
down_revision = '390dfb45e167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_jokes')
    with op.batch_alter_table('jokes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_jokes_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_jokes_categories', 'categories', ['category_id'], ['category_id'])
        batch_op.drop_column('author_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('username')

    with op.batch_alter_table('jokes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.drop_column('category_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('status')
        batch_op.drop_column('content')

    op.create_table('_alembic_tmp_jokes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text_tn', sa.TEXT(), nullable=False),
    sa.Column('text_fr', sa.TEXT(), nullable=True),
    sa.Column('text_en', sa.TEXT(), nullable=True),
    sa.Column('age_group', sa.VARCHAR(length=50), nullable=True),
    sa.Column('era', sa.VARCHAR(length=50), nullable=True),
    sa.Column('region', sa.VARCHAR(length=50), nullable=True),
    sa.Column('acceptability', sa.VARCHAR(length=50), nullable=True),
    sa.Column('delivery_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rhythm', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_jokes_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jokes_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
